[package]
name = "create-link"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
clap = { version = "4.5.16", features = ["derive"] }
get_if_addrs = "0.5.3"
tabled = "0.16.0"
